# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: TestCi

env:
 APPLICATION_NAME       : "MyName" 
 DEPLOY_PACKAJE_NAME    : "Name-for-Deploy-ver-${{ github.sha }}"

on:
  push:
   branches: 
    - main

jobs:
  myTest:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in test
      run: echo "Hello World from testing myTest job"
    
    - name: Execure few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
        
        
  my_deploy: 
   runs-on: ubuntu-latest
   needs: [myTest]
   steps:
     - name: Print Hello Message in deploy
       run: echo "Hello World from Deploy job"
       
     - name: Deployment package
       run: echo "Deploy package name is ${{ env.DEPLOY_PACKAJE_NAME }}"
